### ISSUE TITLE
Unable to use inside a pyinstaller package

### ISSUE THREAD

**Issue by SimonIT** [looking-for-a-job/applescript.py#3]
Hello,

I'm using this wonderful lib in my program https://github.com/SimonIT/spotifylyrics to read the title of Spotify to detect the current playing song.

Everything works fine, until I try to distribute it via pyinstaller.

This is the command I use to generate the SpotifyLyrics.app:
https://github.com/SimonIT/spotifylyrics/blob/6ff9ed03ee431f9935c11bb3f19e94f1d600abcc/.travis.yml#L53
You can remove the `-w` flag to see the following error message during executing the resulting executable:

```python3
Traceback (most recent call last):
  File "SpotifyLyrics.pyw", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "backend.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "applescript/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "only/__init__.py", line 48, in <module>
  File "public/__init__.py", line 65, in add
IndexError: list index out of range
[15076] Failed to execute script SpotifyLyrics
```

**Comment by andrewpetrochenkov** [comment]
"public" deleted. should work now

**Comment by SimonIT** [comment]
Works like a charm, thank you!
